name: roster
description: A simple roster app scaffold
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.2
  pdf: ^3.11.0
  printing: ^5.13.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
